package com.example.demo.model.dbentities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.UUID;

@AllArgsConstructor
@Data
@Entity
@Table(name = "users")
public class User {

   /* @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //The primary key is generated by the database using an auto-increment feature.
            //GenerationType.SEQUENCE - JPA to manage key generation but rely on a specific sequence generator
            //GenerationType.TABLE - JPA stores the primary key generation values in a separate table and manages them manually.
            //GenerationType.AUTO - JPA automatically picks an appropriate strategy based on the database's capabilities (vary depending on the database)
    Long id;*/
    @Id
    private String id;

    @Column(nullable = false)
    String firstName;
    @Column(nullable = false)
    String lastName;
    @Column(nullable = false, unique = true)
    String email;

    public User() {
        // Generating unique session ID when the object is created
        this.id = UUID.randomUUID().toString();
    }
}
